### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by wagerfield** [Freyskeyd/atom-alignment#1]
Hi @Freyskeyd,

I just installed your package and it does not appear to be working? I have tried calling the command using both the keyboard shortcut `cmd+ctrl+a` and through the `command-panel` and nothing happens?

Not that I imagine it matters, but I have a simple JavaScript file:

``` JavaScript
var A = 0;
var AB = 1;
var ABC = 2;
```

...with three cursors located to the left of the 3 `=` characters when I trigger your script.

I just started using Atom today, so not sure if I'm being really silly?!

**Comment by papermoon1978** [comment]
Just for the record ... multi cursor alignment works now in the current release 0.11.0. There is unfortunately a bug leading to some duplicate characters (sorry, sleepy me ...) but this should be fixed in the upcoming release.

**Comment by mustafawm** [comment]
still not working!
on Mac, trying `ctrl+alt+a`
v.1.4.0

**Comment by ramz225** [comment]
this isn't working on my mac is there something new? The package isn't available either?
