### ISSUE TITLE
alignment for ruby: json style version of hashrocket

### ISSUE THREAD

**Issue by torsday** [Freyskeyd/atom-alignment#16]
### json-style version of hashrocket...
```ruby
shared_assessment_1 = Assessment.create!(
  name: "seed_me #{lsn.title}",
  lesson: lsn,
  template: false,
  publish: true,
  online: true)
```

### breaks to
```ruby
shared_assessment_1 = Assessment.create!(
  name     : "seed_me #{lsn.title}",
  lesson   : lsn,
  template : false,
  publish  : true,
  online   : true)
```

### should be
```ruby
shared_assessment_1 = Assessment.create!(
  name:     "seed_me #{lsn.title}",
  lesson:   lsn,
  template: false,
  publish:  true,
  online:   true)
```

### or
```ruby
shared_assessment_1 = Assessment.create!(
      name: "seed_me #{lsn.title}",
    lesson: lsn,
  template: false,
   publish: true,
    online: true)
```

**Comment by papermoon1978** [comment]
This will work in the upcoming release (not released yet) with multiple cursor alignment. Just place different cursors like this (| are marker for the cursor position) and start the alignment

```
   name: |"seed_me #{lsn.title}",
   lesson: |lsn,
   template: |false,
   publish: |true,
   online: |true)
```

This will transform the line to your first mentioned expected result. Please let me know if you are fine with this. Of course I could also add an option to the settings to align the lines in hashrocket style but I'm unsure if this will be used often.
