### ISSUE TITLE
what is the key binding( Atom-alignment ) in window

### ISSUE THREAD

**Issue by Robert-Janagap** [Freyskeyd/atom-alignment#18]
hard to understand the ctr+cmd a

**Comment by jesusiniesta** [comment]
It doesn't make any sense for windows. 

I'll tell you, however, how to change it: 
- copy it (in packages -> atom-alignment -> keybindings, click on the little clipboard icon left to the keybinding)
- go to Keybindings, click on "your keymap file" at the top
- paste at the end of the keymap.cson file
- replace "ctrl-cmd-e" with, for instance, "ctrl-alt-e"

that worked just fine for me on Linux

**Comment by papermoon1978** [comment]
solved in 0.11.0

on OSX the key binding is ctrl+cmd+a while on Linux on Windows it is ctrl+alt+a

**Comment by Robert-Janagap** [comment]
thanks @papermoon1978
