### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by ricardodovalle** [Freyskeyd/atom-alignment#20]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:55:11)
Object.activate (/Users/ricardodovalle/.atom/packages/atom-alignment/lib/atom-alignment.coffee:10:13)
```

**Comment by papermoon1978** [comment]
solved in 0.11.0
