### ISSUE TITLE
I can't allign `|`

### ISSUE THREAD

**Issue by isidrorg** [Freyskeyd/atom-alignment#21]
I want to use this package to allign my markdown tables but it looks like that it doesn't word for this  symbol `|`.

>Yes, I have added this to the package settings: `Alignment Space Chars: =, :, |, ", ', =>`

**Comment by despairblue** [comment]
:+1:  also can't get it to work with a pipe

**Comment by papermoon1978** [comment]
Could you please try my fork (you will have to add the pipe to the "Align By" characters, though? Btw you'll also need the lodash package (apm install lodash in the package folder)

**Comment by despairblue** [comment]
Will try tomorrow. looks promising!

**Comment by papermoon1978** [comment]
solved in 0.11.0
