### ISSUE TITLE
Alignment brings everything to far left

### ISSUE THREAD

**Issue by MaxGiting** [Freyskeyd/atom-alignment#24]
When I use the shortcut to align arrays it always pulls all of the data to the left but leaves 1 space between the beginning of the line and the first character. Shouldn't it keep all the values in the same starting position as they are often following indentation from classes or functions.

![alignment_issue](https://cloud.githubusercontent.com/assets/9828591/6452587/a7cc69e2-c12e-11e4-8a5a-7ce51cdcc0f1.gif)

**Comment by papermoon1978** [comment]
Hmm, works fine here. Are you using tabs or spaces for indentation ? What are your package settings ?

**Comment by MaxGiting** [comment]
Atom-alignment v0.11.0 no custom settings. Just as default when installed.

Here are some of my settings. Tell me if you want any more.

Setting | Set / Value
------------ | -------------
Soft Tabs | True
Soft Wrap | False
Tab Length | 2

**Comment by papermoon1978** [comment]
Ok, after having another look I think I can reproduce it. Looks like is has something to do if spaces and tabs are mixed on the same row. Can you please try my fork https://github.com/papermoon1978/atom-alignment ? Just replace the aligner.coffee

**Comment by MaxGiting** [comment]
I've been running with this fork for a few hours and yes it seems to fix the issue I had completely!
Thank you!

**Comment by papermoon1978** [comment]
Thanks for testing. Looks I've overseen something while doing the rewrite. Sorry. But glad it's working now. I'll create another pull request so this should be part of the next patch.
