### ISSUE TITLE
Alignment no longer works since 0.11.0

### ISSUE THREAD

**Issue by schanq** [Freyskeyd/atom-alignment#25]
Ctrl+Cmd+a no longer works for me on my macbook. Worked perfectly fine prior to 0.11.0 update.

**Comment by papermoon1978** [comment]
Hmm, works just fine here. Could you please copy/paste the lines you're trying to align to this issue or upload a screenshot?

**Comment by schanq** [comment]
![screen shot 2015-03-04 at 03 33 59](https://cloud.githubusercontent.com/assets/2590123/6477777/713f76d4-c21f-11e4-98a3-62f6899d9939.png)

**Comment by papermoon1978** [comment]
Hmm, I was expecting some complicated lines, but this looks quite simple. Can currently only test this on Windows and also your example is working fine here. Today evening I can check this on my MacBook but would be a little weird if this failed to work. Could you please check if the "=" is still part of the package settings "Align By" characters ? Also please try to call "Align Multiple" via menu Packages -> atom-alignment. If this works, please use the keybinding resolver to check if the command is actually called.

**Comment by schanq** [comment]
![screen shot 2015-03-04 at 15 17 24](https://cloud.githubusercontent.com/assets/2590123/6486329/1608d4f0-c282-11e4-9a0d-4b0f3ea03366.png)


![screen shot 2015-03-04 at 15 17 37](https://cloud.githubusercontent.com/assets/2590123/6486327/10b9ddbe-c282-11e4-847a-a2532151dccb.png)


![screen shot 2015-03-04 at 15 20 14](https://cloud.githubusercontent.com/assets/2590123/6486317/046b33dc-c282-11e4-8d30-fae8756ba46c.png)

And here's the atom-alignment.cson linked from key bindings resolver:
'.platform-darwin atom-text-editor':
    'ctrl-cmd-a': 'atom-alignment:alignMultiple'
'.platform-win32 atom-text-editor, .platform-linux atom-text-editor':
    'ctrl-alt-a': 'atom-alignment:alignMultiple'

**Comment by papermoon1978** [comment]
Looks quite good. But strange thing is that your settings look somewhat corrupted (the explanatory text is missing, ...) Could you please send me another screenshot showing the value for "align by"?

![atom](https://cloud.githubusercontent.com/assets/4062007/6486603/4ad4d986-c28c-11e4-9caa-afc42adbc472.png)

**Comment by schanq** [comment]
They must be corrupted as my settings don't have "Align By" or "Add Space Postfix" properties... I have tried reinstalling several times and never see those settings.

**Comment by schanq** [comment]
Ah! I've just updated Atom itself and alignment now works again..! 
Sorry for adding to your workload!!!

**Comment by papermoon1978** [comment]
Good to know. So many thanks for reporting this. :-)
