### ISSUE TITLE
Indentation Breaking When Using Hard Tabs

### ISSUE THREAD

**Issue by robneu** [Freyskeyd/atom-alignment#27]
This works great when files are indented with soft tabs, but WordPress coding standards require hard tabs for all PHP files. I'm not sure if it's a setting that I'm not quite understanding, but when aligning a block with hard tabs the indention is replaced with a single space.

The alignment works fine, but the entire block is then indented with a single space rather than whatever the previous indentation was. 

### Gif for a Better Explanation:

![notify](https://cloud.githubusercontent.com/assets/2184093/6540684/c0f1348e-c471-11e4-9968-f1d763fe9a5d.gif)

**Comment by papermoon1978** [comment]
This is already fixed and will be part of the next release. In the meantime you could use the aligner.coffee from the Github repo.

**Comment by robneu** [comment]
Ah, sweet. :+1: I noticed the other issue after I opened this one, but wasn't sure if they were the same. I'll go ahead and close this out for now and reopen if there's still problems after the update. Thanks!

**Comment by papermoon1978** [comment]
Thanks for reporting anyway :-)
