### ISSUE TITLE
Atom-Alignment Throws Deprecation Cop Warning

### ISSUE THREAD

**Issue by mattlovaglio** [Freyskeyd/atom-alignment#29]
The package seems to generate a strange error since the last update. It triggers a deprecation cop warning that associates the error with the Atom Core. I opened a previous ticket with the Atom. You can reference the thread here: atom/atom#6278

I'm on and running: 
MacBook Pro Retina
OS X Yosemite 10.10.2
Atom Version 0.189.0 (0.189.0)

Here's a screenshot of the Deprecation Cop error.

![deprecation cop - atom](https://cloud.githubusercontent.com/assets/10821303/7032049/fe43f97c-dd3d-11e4-9f0b-b64148814eb3.jpeg)

**Comment by Freyskeyd** [comment]
done in #31
