### ISSUE TITLE
Package.activateResources is deprecated.

### ISSUE THREAD

**Issue by dusanvudragovic** [Freyskeyd/atom-alignment#31]
Hi Simon,

With Atom version 0.196.0 on MacOS the plugin reports the following problem:

```
The context menu CSON format has changed. Please see
https://atom.io/docs/api/latest/ContextMenuManager
```

Due to this, it is not possible to use atom-alignment within the Atom-0.196.0. I have managed to solve this problem by replacing

```
'context-menu':
  '.overlayer':
    'Enable atom-alignment': 'atom-alignment:align'
```

with 

```
'context-menu':
  '.overlayer': [{ 'Enable atom-alignment': 'atom-alignment:align' }]
```

in ```~/.atom/packages/atom-alignment/menus/atom-alignment.cson``` file. Hopefully, this will help you in debugging.

Best regards, Dusan

**Comment by miketheman** [comment]
Dupes: #32, #33

**Comment by Freyskeyd** [comment]
Done in a32723dc258a5ef20b016f7570af69ea54d1a6d4
