### ISSUE TITLE
Suggestions on undo grouping and cursor pos

### ISSUE THREAD

**Issue by tinymins** [Freyskeyd/atom-alignment#39]
1. When I align 10 lines by once, It will create 10 undo grouping, which means I need to press `ctrl+z` for 10 times to revert the changing. Is there any way to merge those 10 steps into one?(In sublime I just need to press `ctrl+z` for one time when undo the change).
2. After alignment, the cursor will goto the end of each line, but in sublime the cursor will just stay at the origin pos. Is there any way to change this?

Thanks xD

**Comment by papermoon1978** [comment]
Currently this is the way it works. I'll keep this suggestion open and will come back to this the next weeks.

**Comment by tinymins** [comment]
Thanks~

**Comment by dodekeract** [comment]
Any news on this one? I find this rather annoying to work with.

**Comment by Kadrian** [comment]
I'd love to have a single undo group as well, any hints on how to implement it? Can I help?

**Comment by Kadrian** [comment]
Any news on when these PRs can be merged?

**Comment by Freyskeyd** [comment]
A new version has been bumped.

Reopen if needed.
