### ISSUE TITLE
Version of this package that Atom installed is out of date?

### ISSUE THREAD

**Issue by JarrettBillingsley** [Freyskeyd/atom-alignment#68]
Hey, I installed this package in Atom, and it worked mostly how I wanted but I made a couple changes (undo grouping and making cursors stay where they are instead of moving to the end of the line).

Then I came here to make a PR, and found that both those issues have been fixed; one yesterday, and one nearly a year ago.

I checked Atom's settings, and yep, it says I have version 0.12.1 installed. And this repo says it's 0.12.1. The code in this repo is very different from the code in the package that Atom installed.

What's going on here? Why would Atom have installed a version that is a year or more old?

**Comment by JarrettBillingsley** [comment]
Ohhh okay. Thanks!

**Comment by Freyskeyd** [comment]
Hello @JarrettBillingsley and @jcmarchi 

I will update the npm package soon

**Comment by Freyskeyd** [comment]
done

**Comment by JarrettBillingsley** [comment]
Great, thanks! 👍
