### ISSUE TITLE
Alignment appending extra characters at end of line

### ISSUE THREAD

**Issue by tlienart** [Freyskeyd/atom-alignment#70]
I think this example will speak for itself:

```julia
tauf = bounce.tau
pq[fidx] = t+tauf
```

selecting both lines and pressing Cmd+Control+A, I get:

```julia
tauf     = bounce.tau.tau
pq[fidx] = t+tauf
```

### specs

* Atom 1.15.0
* atom-alignment 0.12.1
* macOS Sierra 10.12.1

**Edit**:

Interestingly, it seems to depend on my selection. When selecting both lines plus the blank line above, the alignment works as expected. More experimenting leads the following added characters (each time selecting exactly the two lines)

```
tauf= bounce.tau
pq[fidx] = t+tauf
```

to

```
tauf     = bounce.taue.tau
pq[fidx] = t+tauf
```

while

```
tauf    = bounce.tau
pq[fidx] = t+tauf
```

leads to

```
tauf     = bounce.tauu
pq[fidx] = t+tauf
```

So if it needs to push the equal by (say) 2 characters, it takes the last two characters of the line and adds them. Not sure why that is...

**Comment by sbcgua** [comment]
:+1:

**Comment by nickv2002** [comment]
I have the same issue.  This seems to be something that started happening with a recent update because it didn't used to happen at all. Not sure if it's an Atom update or an update to this plugin but it might be worth rolling back to earlier versions to test.

**Comment by morcegon** [comment]
Same here! I'm on Mac OS Sierra, Atom 1.15.0 and atom-alignment 0.12.1

**Comment by tlienart** [comment]
not super constructive but the [other alignment package](https://atom.io/packages/alignment) does not suffer from that issue.

**Comment by MatthieuLemoine** [comment]
This issue occurs only on the first line if the first line's ``=`` or ``:`` must be left-padded.

**Comment by eltian** [comment]
I'm having the same issue, but it happens on the last line being aligned.

Atom Version: 1.16.0
atom-alignment: 0.12.1

**Comment by eltian** [comment]
#72 solves the problem for me. Thanks!
