### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by lalogalindo** [Freyskeyd/atom-alignment#71]
When I try to align something like this:

![screen shot 2017-04-18 at 10 19 50 pm](https://cloud.githubusercontent.com/assets/1209535/25162031/2ca94b06-2485-11e7-9b79-a9cbfe0cd313.png)

It always does something like this:

![screen shot 2017-04-18 at 10 20 27 pm](https://cloud.githubusercontent.com/assets/1209535/25162037/43699648-2485-11e7-888e-ed9eb7d584dc.png)

It repeats the first line's last 2 characters.

**Comment by MatthieuLemoine** [comment]
Duplicate of #70 ?

**Comment by lalogalindo** [comment]
Yes, it seems that way.

**Comment by Freyskeyd** [comment]
I tried and it seems resolve.

Reopen if needed.
