### ISSUE TITLE
Atom `alignment` package

### ISSUE THREAD

**Issue by blakeembrey** [Freyskeyd/atom-alignment#80]
I haven't checked if it's possible, but if it is, would you like to take https://atom.io/packages/alignment? I don't really use Atom anymore and would love to remove my package.

**Comment by Freyskeyd** [comment]
Hello @blakeembrey,

I don't know if it's a good things or important things but when I created this repository it was the 'convention' to use `atom-` for a package.

I don't know if you can redirect your package on another url.

Thank's to propose by the way :)

**Comment by blakeembrey** [comment]
Convention to prefix `atom-` on the Atom registry? That seems odd and I definitely haven't seen that with other packages. You can look at the package list (https://atom.io/packages) and see that only a few use `atom-` prefixes. I don't control the registry so won't be able to implement a redirect, so I'll close this for now. If you'd like to use it in the future, let me know.
