### ISSUE TITLE
Unexpected behaviour with angular directive

### ISSUE THREAD

**Issue by anotheri** [Freyskeyd/atom-alignment#9]
It returns an unexpected alignment result in case of this:
```
scope: {
  /* start selection */
  mapRef: '=',
  stateData: '=',
  polygons: '=',
  onWirecenterClicked: '=',
  onShowResultsChange: '='
  /* end selection */
}
```

**Comment by papermoon1978** [comment]
solved in 0.11.0 if you exclusively set the character ":" as alignment char. Of course you can also use multiple cursors for the alignment. Then there is no need to change the settings, just place the cursors in front of each ":"
